# Generated by Django 5.0.1 on 2024-01-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Web', '웹 개발'), ('Game', '게임 개발'), ('Data', '데이터')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deploy_url', models.URLField(blank=True, null=True)),
                ('tech_stack', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
