# Generated by Django 5.0.1 on 2024-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Project', '웹 개발'), ('Game Project', '게임 개발'), ('Data Project', '데이터')], max_length=32),
        ),
    ]
