# Generated by Django 5.0.1 on 2024-01-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.ImageField(default='', upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(default='', upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(default='', upload_to='projects/'),
        ),
    ]
