# Generated by Django 5.0.1 on 2024-01-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_image1_project_image2_project_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(default='', upload_to='assets/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(default='', upload_to='assets/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(default='', upload_to='assets/projects/'),
        ),
    ]
